// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaV5IuUOkwQ70N146hRxpk-nRBySkyeE',
    appId: '1:667901837097:web:32c9a7e417fd9088f8c138',
    messagingSenderId: '667901837097',
    projectId: 'data-base-belajar',
    authDomain: 'data-base-belajar.firebaseapp.com',
    storageBucket: 'data-base-belajar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97akdxr1huPH35p0G7R-mLzK2OadGBXc',
    appId: '1:667901837097:android:a01144e0b83b4731f8c138',
    messagingSenderId: '667901837097',
    projectId: 'data-base-belajar',
    storageBucket: 'data-base-belajar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvoo9j87ZUTVVmWw803OWV-DU6-IF1vMU',
    appId: '1:667901837097:ios:911d40e956d14fdbf8c138',
    messagingSenderId: '667901837097',
    projectId: 'data-base-belajar',
    storageBucket: 'data-base-belajar.appspot.com',
    iosBundleId: 'com.example.dataBaseBelajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvoo9j87ZUTVVmWw803OWV-DU6-IF1vMU',
    appId: '1:667901837097:ios:e496bb2dad4d5f50f8c138',
    messagingSenderId: '667901837097',
    projectId: 'data-base-belajar',
    storageBucket: 'data-base-belajar.appspot.com',
    iosBundleId: 'com.example.dataBaseBelajar.RunnerTests',
  );
}
